### ISSUE TITLE
Question to Conpot - MHN - and deploying Honeypots manually

### ISSUE THREAD

**Issue by utku461** [pwnlandia/mhn#782]
Hey guys,

What would be an common attack on Conpot that would be shown in the attack reports?  and how would i deploy Honeypots manual on MHN for example a other template of conpot.

greetings

Utku

**Comment by d1str0** [comment]
This is two questions in one. Since neither of these are issues they are better suited for the mailing list.

Check the documentation for the conpot project for information on how to use it.

Honeypots are deployed using shell scripts. In the dashboard you can view and edit the installation scripts. Feel free to tweak them as you wish and future deployments of that script will use the edited script.
