### ISSUE TITLE
honeymap/server issue

### ISSUE THREAD

**Issue by Sue1990** [pwnlandia/mhn#811]
I can't start honeymap.

I tried to use below down method to fixed my problem, but it didn't work.

cd /opt/honeymap/server
export GOPATH=/opt/honeymap/server
go get
go build

the error messagees:
go: finding github.com/fzzy/sockjs-go v0.0.0-20131128051453-1ba9e8c64209
go: github.com/fzzy/sockjs-go@v0.0.0-20131128051453-1ba9e8c64209: git fetch -f https://github.com/fzzy/sockjs-go refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/xxx/go/pkg/mod/cache/vcs/98a8732e28275896133f4ab234822e2b5fe02b57ed4763a12c3456b228e6ad03: exit status 128:
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
go: error loading module requirements

**Comment by Finch4** [comment]
Same

**Comment by RedbeardTheSecurityViking** [comment]
Looks like the "https://github.com/fzzy/sockjs-go" repo either no longer exists or is private. If you try to access it, it returns a 404. Without it, the "make" fails for Honeymap and no /opt/honeymap/server/server file is created and therefor the reference to it in the Supervisorctl config fails. Not sure what the actual fix would be here since it seems like based off "https://github.com/pwnlandia/honeymap/blob/master/server/go.mod" indicates is a required package.

**Comment by nafswteam** [comment]
Download the souce code for only  honeymap and reinstall from https://github.com/fw42/honeymap

**Comment by Sue1990** [comment]
@nafswteam thanks

**Comment by TGuerillon** [comment]
> Download the souce code for only honeymap and reinstall from https://github.com/fw42/honeymap

I don't see how this workaround works as it is also needs to download fzzy/sockjs-go

**Comment by Power-tile** [comment]
@nafswteam May I ask how did you download the source code for only honeymap? I cloned the repo and ran `go get`, but it still requires `sockjs-go` and throws error.

**Comment by blackph0en1x** [comment]
The problems seems that "github.com/fzzy/sockjs-go/sockjs" is not available anymore. Any hints on how to get this fixed?
Anybody has a clone copy of this repo?
I tried switching it with "github.com/igm/sockjs-go/sockjs" but it still exits with errors.
